apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-api
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 3001
    # - protocol: "TCP"
    #   port: 3000
    #   targetPort: 3000
