# version: "3.8"
services:
  mongoserver:
    container_name: mongoserver
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: joydip
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  goals-backend:
    container_name: goals-backend
    # build: ./backend
    image: "goals-node:latest"
    build:
      context: ./backend
      dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    environment:
      - MONGODB_DNS_NAME=mongoserver
    depends_on:
      - mongoserver
  goals-frontend:
    container_name: goals-frontend
    image: "goals-react:latest"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - goals-backend

volumes:
  data:
    name: data
  logs:
    name: logs
# networks:
#   fav-network:
#     name: ""

