apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-message-app
  labels:
    app: kube-dep
spec:
  selector:
    matchLabels:
      app: kube-pod
  replicas: 2
  template:
    metadata:
      name: kube-message-pod
      labels:
        app: kube-pod
    spec:
      containers:
        - name: kube-message-container
          image: joydipdocker/kube-app:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
