apiVersion: v1
kind: Service
metadata:
  name: kube-message-service
  labels:
    app: kube-service
spec:
  selector:
    app: kube-pod
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: "TCP"
      targetPort: 3000
