apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-pod
  template:
    metadata:
      labels:
        app: story-pod
    spec:
      containers:
        - name: story-container
          image: joydipdocker/story-app-image:v2
          env:
            - name: STORY_FOLDER
              value: "storydata"
          volumeMounts:
            - name: story-volume
              mountPath: /app/storydata
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pv-claim
